<a href="https://colab.research.google.com/github/chw8207/pytorch_study/blob/main/nn_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 함수 간단 예시
 - nn.Linear() : 선형회귀모델
 - nn.functional.mse_loss() : 평균제곱오차

In [2]:
import torch.nn as nn
model = nn.Linear(input_dim, output_idm)

In [ ]:
import torch.nn.functional as F
cost = F.mse_loss(prediction, y_train)

### 단순 선형회귀 구현

In [20]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [21]:
torch.manual_seed(1)

In [22]:
# 데이터
X_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [23]:
# 모델 선언 및 초기화
# 단순 선형회귀이므로 input_dim, output_dim 모두 1
model = nn.Linear(1,1)

In [24]:
# model.parameters() : 가중치와 편향 불러오기
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [25]:
# optimzer 설정
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [26]:
nb_epochs = 2000
for epoch in range(nb_epochs+1) : 
  # H(x) 계산
  prediction = model(X_train)

  # cost 계산
  cost = F.mse_loss(prediction, y_train)

  # cost로 H(x) 개선
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%100==0 : 
    print(f'Epoch {epoch:4d}/{nb_epochs} cost: {cost.item():.6f}')

Epoch    0/2000 cost: 13.103541
Epoch  100/2000 cost: 0.002791
Epoch  200/2000 cost: 0.001724
Epoch  300/2000 cost: 0.001066
Epoch  400/2000 cost: 0.000658
Epoch  500/2000 cost: 0.000407
Epoch  600/2000 cost: 0.000251
Epoch  700/2000 cost: 0.000155
Epoch  800/2000 cost: 0.000096
Epoch  900/2000 cost: 0.000059
Epoch 1000/2000 cost: 0.000037
Epoch 1100/2000 cost: 0.000023
Epoch 1200/2000 cost: 0.000014
Epoch 1300/2000 cost: 0.000009
Epoch 1400/2000 cost: 0.000005
Epoch 1500/2000 cost: 0.000003
Epoch 1600/2000 cost: 0.000002
Epoch 1700/2000 cost: 0.000001
Epoch 1800/2000 cost: 0.000001
Epoch 1900/2000 cost: 0.000000
Epoch 2000/2000 cost: 0.000000


In [28]:
# 임의의 입력 4를 선언하기
new_var = torch.FloatTensor([[4.0]])

# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)

# y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된 것
print('훈련 후 입력이 4일 때의 예측값 :', pred_y)

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9989]], grad_fn=<AddmmBackward0>)


In [29]:
# 학습 후의 W와 b의 값을 출력
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


### 다중 선형회귀 구현

In [30]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [31]:
torch.manual_seed(1)

In [32]:
# 데이터
X_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])