<a href="https://colab.research.google.com/github/chw8207/pytorch_study/blob/main/nn_module(logistic).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 파이토치의 nn.Linear와 nn.Sigmoid로 로지스틱 회귀 구현

In [15]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [16]:
torch.manual_seed(1)

In [17]:
# 훈련 데이터 텐서로 선언하기
X_data = [[1,2], [2,3], [3,1], [4,3], [5,3], [6,2]]
y_data = [[0],[0],[0],[1],[1],[1]]
X_train = torch.FloatTensor(X_data)
y_train = torch.FloatTensor(y_data)

In [18]:
# nn.Sequential() : nn.Module 층을 차례로 쌓을 수 있게 함
model = nn.Sequential(
    nn.Linear(2,1),
    nn.Sigmoid()  # 출력은 시그모이드 함수를 거침
)

In [19]:
model(X_train)

tensor([[0.4020],
        [0.4147],
        [0.6556],
        [0.5948],
        [0.6788],
        [0.8061]], grad_fn=<SigmoidBackward0>)

In [20]:
# 경사하강법으로 훈련시키기
optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs=1000
for epoch in range(nb_epochs+1) : 
  # H(x) 계산
  hypothesis = model(X_train)

  # cost 계산
  cost = F.binary_cross_entropy(hypothesis, y_train)

  # cost로 H(x) 개선
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%20==0 : 
    prediction = hypothesis >= torch.FloatTensor([0.5])
    correct_prediction = prediction.float() == y_train   # 실제값과 일치하는 경우만 True로 간주
    accuracy = correct_prediction.sum().item()/len(correct_prediction)
    print(f'Epoch {epoch:4d}/{nb_epochs} Cost: {cost.item():.6f} Accuracy: {accuracy*100:2.2f}%')

Epoch    0/1000 Cost: 0.539713 Accuracy: 83.33%
Epoch   20/1000 Cost: 0.441875 Accuracy: 66.67%
Epoch   40/1000 Cost: 0.316358 Accuracy: 83.33%
Epoch   60/1000 Cost: 0.220498 Accuracy: 100.00%
Epoch   80/1000 Cost: 0.157299 Accuracy: 100.00%
Epoch  100/1000 Cost: 0.134272 Accuracy: 100.00%
Epoch  120/1000 Cost: 0.118297 Accuracy: 100.00%
Epoch  140/1000 Cost: 0.105779 Accuracy: 100.00%
Epoch  160/1000 Cost: 0.095704 Accuracy: 100.00%
Epoch  180/1000 Cost: 0.087420 Accuracy: 100.00%
Epoch  200/1000 Cost: 0.080486 Accuracy: 100.00%
Epoch  220/1000 Cost: 0.074595 Accuracy: 100.00%
Epoch  240/1000 Cost: 0.069526 Accuracy: 100.00%
Epoch  260/1000 Cost: 0.065118 Accuracy: 100.00%
Epoch  280/1000 Cost: 0.061247 Accuracy: 100.00%
Epoch  300/1000 Cost: 0.057820 Accuracy: 100.00%
Epoch  320/1000 Cost: 0.054764 Accuracy: 100.00%
Epoch  340/1000 Cost: 0.052022 Accuracy: 100.00%
Epoch  360/1000 Cost: 0.049546 Accuracy: 100.00%
Epoch  380/1000 Cost: 0.047299 Accuracy: 100.00%
Epoch  400/1000 Cost: 0

In [21]:
# 예측값 확인
model(X_train)

tensor([[2.7616e-04],
        [3.1595e-02],
        [3.8959e-02],
        [9.5624e-01],
        [9.9823e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward0>)

In [22]:
# 훈련 후 W, b 출력하기
print(list(model.parameters()))

[Parameter containing:
tensor([[3.2534, 1.5181]], requires_grad=True), Parameter containing:
tensor([-14.4839], requires_grad=True)]
