<a href="https://colab.research.google.com/github/chw8207/pytorch_study/blob/main/softmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn.functional as F

In [2]:
torch.manual_seed(1)

###  파이토치로 소프트맥스의 비용 함수 구현하기 (로우-레벨)

In [3]:
z = torch.FloatTensor([1,2,3])

In [4]:
# 텐서를 소프트맥스 함수 입력으로 사용하고 확인해보기
hypothesis = F.softmax(z, dim=0)
print(hypothesis)

tensor([0.0900, 0.2447, 0.6652])


In [5]:
# 원소들의 값의 합이 1인지 확인해보기
hypothesis.sum()

tensor(1.)

In [6]:
# 임의의 3X5행렬의 크기를 가진 텐서 선언
z = torch.rand(3,5, requires_grad=True)

In [7]:
# 텐서에 소프트맥스함수 적용
# 텐서 차원이 2차원이라 두 번째 차원 : dim=1
hypothesis = F.softmax(z, dim=1)
print(hypothesis)

tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward0>)


In [9]:
# 각 샘플에 대한 임의의 레이블 만들기
y = torch.randint(5,(3,)).long()
print(y)

tensor([2, 1, 0])


In [10]:
# 모든 원소가 0의 값을 가진 3 × 5 텐서 생성
y_one_hot = torch.zeros_like(hypothesis)
y_one_hot.scatter_(1,y.unsqueeze(1),1)

tensor([[0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.]])

In [11]:
# 비용함수 구현하기
cost = (y_one_hot*-torch.log(hypothesis)).sum(dim=1).mean()
print(cost)

tensor(1.6682, grad_fn=<MeanBackward0>)
