<a href="https://colab.research.google.com/github/chw8207/pytorch_study/blob/main/tensor_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# 뷰(view) : 원소의 수를 유지하면서 텐서의 크기 변경
# numpy에서 reshape와 같음

In [3]:
import numpy as np
import torch

In [4]:
t = np.array([[[0,1,2], [3,4,5]],
              [[6,7,8], [9,10,11]]])

ft = torch.FloatTensor(t)

In [5]:
print(ft.shape)

torch.Size([2, 2, 3])


In [7]:
# 3차원 텐서에서 2차원 텐서로 변경하기
#-1 : 파이토치에게 맡긴다.(-1,3)은(?,3)
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [8]:
# 3차원 텐서의 크기 변경
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [11]:
# 스퀴즈(Squeeze) : 1인 차원을 제거한다.
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
