<a href="https://colab.research.google.com/github/chw8207/pytorch_study/blob/main/tensor_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
cd /content/drive/MyDrive/Colab Notebooks/파이토치공부/pytorch_study

/content/drive/MyDrive/Colab Notebooks/파이토치공부/pytorch_study


In [ ]:
!git clone https://chw8207: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@github.com/chw8207/pytorch_study.git

Cloning into 'pytorch_study'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), 619 bytes | 16.00 KiB/s, done.


### 넘파이로 텐서 만들기

In [ ]:
import numpy as np

In [ ]:
# 1차원 텐서 벡터 만들기
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [ ]:
# 벡터의 차원과 크기
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [ ]:
# 2차원 텐서 벡터 만들기
t = np.array([[1.,2.,3.], [4.,5.,6.], [7.,8.,9.],
              [10.,11.,12.]])

In [ ]:
# 벡터의 차원과 크기
print('Rank of t :', t.ndim)
print('Shape of t :', t.shape)

Rank of t : 2
Shape of t : (4, 3)


### 파이토치 텐서 선언하기

In [1]:
import torch

In [ ]:
# 1차원 텐서 벡터 만들기
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [ ]:
# 차원과 크기
# dim() : 차원 확인
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [ ]:
# 인덱스 접근과 슬라이싱
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [ ]:
# 2차원 텐서 벡터 만들기
t = torch.FloatTensor([[1.,2.,3.], [4.,5.,6.], [7.,8.,9.],
                      [10.,11.,12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
# 차원과 크기 확인하기
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [ ]:
# 슬라이싱 해보기
print(t[:,1])
print(t[:,1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [ ]:
# # 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져온다
print(t[:,:-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [ ]:
# 브로드캐스팅(Broadcasting) : 자동으로 크기를 맞춰서 연산이 가능하게끔 함

In [ ]:
# 같은 크기일 때 연산
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [ ]:
# 벡터와 스칼라의 연산(크기가 다름)
# vector+scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])      # [3]->[3,3]으로 브로드캐스팅됨
print(m1+m2)

tensor([[4., 5.]])


In [ ]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[3]])
print(m1+m2)

tensor([[4., 5.],
        [4., 5.]])


In [ ]:
# 행렬 곱셈 vs 곱셈
# 행렬 곱셈 : matmul()
# (원소)곱셈 : mul() 또는 *

In [4]:
# 행렬 곱셈
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1], [2]])

print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1.matmul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [7]:
# (원소)곱셈
# 브로드캐스팅 된 후 곱셈실행됨
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1], [2]])

print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1*m2)
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [8]:
# 평균
# 1차원 벡터 평균
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [9]:
# 2차원 행렬 평균
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [10]:
print(t.mean())

tensor(2.5000)


In [11]:
# 차원(dim)을 인자로 주는 경우
# 해당 인자 제거한다.
# dim=0 이면 행 제거
print(t.mean(dim=0))

tensor([2., 3.])


In [12]:
# dim=1이면 열 제거
print(t.mean(dim=1))

tensor([1.5000, 3.5000])
