<a href="https://colab.research.google.com/github/chw8207/pytorch_study/blob/main/tensor_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# 뷰(view) : 원소의 수를 유지하면서 텐서의 크기 변경
# numpy에서 reshape와 같음

In [1]:
import numpy as np
import torch

In [ ]:
t = np.array([[[0,1,2], [3,4,5]],
              [[6,7,8], [9,10,11]]])

ft = torch.FloatTensor(t)

In [ ]:
print(ft.shape)

torch.Size([2, 2, 3])


In [ ]:
# 3차원 텐서에서 2차원 텐서로 변경하기
#-1 : 파이토치에게 맡긴다.(-1,3)은(?,3)
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [ ]:
# 3차원 텐서의 크기 변경
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [ ]:
# 스퀴즈(Squeeze) : 1인 차원을 제거한다.
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [ ]:
# 언스퀴즈(Unsqueeze) : 특정 위치에 1인 차원 추가
ft = torch.FloatTensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [ ]:
# 첫 번째 차원에 1인 차원 추가하기
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
#  2차원으로 바꾸고 싶으면서 첫번째 차원은 1로 바꾸기
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
# 두번째 차원에 1을 추가
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
# 마지막 차원에 1을 추가
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [2]:
# 타입 캐스팅
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [3]:
# float타입으로 변경
print(lt.float())

tensor([1., 2., 3., 4.])


In [4]:
# byte 타입
bt = torch.ByteTensor([True,False,False,True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [5]:
# 타입 변경
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [7]:
# 연결하기(concatenate)
x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[5,6], [7,8]])

In [8]:
# dim=0 : 첫 번째 차원 늘리기
print(torch.cat([x,y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [9]:
# dim=1 : 두 번째 차원 늘리기
print(torch.cat([x,y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [10]:
# 스택킹(Stacking)
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [11]:
# 3개의 벡터 순서대로 쌓기
print(torch.stack([x,y,z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [12]:
# dim=1 : 두 번째 차원이 증가하도록 쌓기
print(torch.stack([x,y,z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [13]:
# ones_like와 zeros_like - 0으로 채워진 텐서와 1로 채워진 텐서
x = torch.FloatTensor([[0,1,2], [2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [14]:
# 동일 크기이지만 0값으로 채워진 텐서
print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [15]:
# 동일 크기이지만 1값으로 채워진 텐서
print(torch.ones_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [17]:
# In-place Operation (덮어쓰기 연산)
x = torch.FloatTensor([[1,2], [3,4]])

In [19]:
print(x.mul(2.)) # 곱하기2를 실행
print(x)         # 기존값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
