<a href="https://colab.research.google.com/github/chw8207/pytorch_study/blob/main/tensor_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
cd /content/drive/MyDrive/Colab Notebooks/파이토치공부/pytorch_study

/content/drive/MyDrive/Colab Notebooks/파이토치공부/pytorch_study


In [2]:
!git clone https://chw8207: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@github.com/chw8207/pytorch_study.git

Cloning into 'pytorch_study'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), 619 bytes | 16.00 KiB/s, done.


### 넘파이로 텐서 만들기

In [3]:
import numpy as np

In [4]:
# 1차원 텐서 벡터 만들기
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [5]:
# 벡터의 차원과 크기
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [6]:
# 2차원 텐서 벡터 만들기
t = np.array([[1.,2.,3.], [4.,5.,6.], [7.,8.,9.],
              [10.,11.,12.]])

In [8]:
# 벡터의 차원과 크기
print('Rank of t :', t.ndim)
print('Shape of t :', t.shape)

Rank of t : 2
Shape of t : (4, 3)


### 파이토치 텐서 선언하기

In [9]:
import torch

In [13]:
# 1차원 텐서 벡터 만들기
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [14]:
# 차원과 크기
# dim() : 차원 확인
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [18]:
# 인덱스 접근과 슬라이싱
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])
