<a href="https://colab.research.google.com/github/chw8207/pytorch_study/blob/main/%ED%85%90%EC%84%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 파이토치 텐서 생성하기기

In [1]:
import torch

In [3]:
# 실수형 Float텐서를 선언하기
ft = torch.FloatTensor([[1,2],
                        [3,4]])

ft

tensor([[1., 2.],
        [3., 4.]])

In [4]:
# Long타입 텐서 선언
lt = torch.LongTensor([[1,2],
                       [3,4]])

lt

tensor([[1, 2],
        [3, 4]])

In [5]:
# Byte타입 텐서 선언
bt = torch.ByteTensor([[1,0],
                       [0,1]])

bt

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

In [7]:
# 임의의 값으로 채워진 원하는 크기의 텐서 만들기
x = torch.FloatTensor(3,2)

x

tensor([[1.1490e-29, 4.5719e-41],
        [1.1490e-29, 4.5719e-41],
        [0.0000e+00, 0.0000e+00]])

### 넘파이 호환

In [8]:
import torch
import numpy as np

In [9]:
# 넘파이 배열 생성
x = np.array([[1,2],
              [3,4]])
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [10]:
# 파이토치 텐서로 변환
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [11]:
# 넘파이 배열로 변환
x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


### 텐서 타입 변환환

In [12]:
# Float 타입을 Long 타입으로 변환하기
ft.long()

tensor([[1, 2],
        [3, 4]])

In [13]:
# Long 타입을 Float 타입으로 변환하기
lt.float()

tensor([[1., 2.],
        [3., 4.]])

### 텐서 크기 구하기

In [14]:
# 3*2*2 텐서 선언하기
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                       [[5,6],
                        [7,8]],
                       [[9,10],
                        [11,12]]])

In [15]:
# 크기 확인
print(x.size())

torch.Size([3, 2, 2])


In [16]:
print(x.shape)

torch.Size([3, 2, 2])


In [17]:
# 특정 차원의 크기 확인하기
print(x.size(1))

2


In [18]:
print(x.shape[1])

2


In [19]:
# 텐서 차원의 개수 확인하기
print(x.dim())

3


In [21]:
print(len(x.size()))

3
