<a href="https://colab.research.google.com/github/chw8207/pytorch_study/blob/main/%ED%85%90%EC%84%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
# 실수형 Float텐서를 선언하기
ft = torch.FloatTensor([[1,2],
                        [3,4]])

ft

tensor([[1., 2.],
        [3., 4.]])

In [4]:
# Long타입 텐서 선언
lt = torch.LongTensor([[1,2],
                       [3,4]])

lt

tensor([[1, 2],
        [3, 4]])

In [5]:
# Byte타입 텐서 선언
bt = torch.ByteTensor([[1,0],
                       [0,1]])

bt

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)