<a href="https://colab.research.google.com/github/chw8207/pytorch_study/blob/main/%ED%85%90%EC%84%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 파이토치 텐서 생성하기기

In [1]:
import torch

In [3]:
# 실수형 Float텐서를 선언하기
ft = torch.FloatTensor([[1,2],
                        [3,4]])

ft

tensor([[1., 2.],
        [3., 4.]])

In [4]:
# Long타입 텐서 선언
lt = torch.LongTensor([[1,2],
                       [3,4]])

lt

tensor([[1, 2],
        [3, 4]])

In [5]:
# Byte타입 텐서 선언
bt = torch.ByteTensor([[1,0],
                       [0,1]])

bt

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

In [7]:
# 임의의 값으로 채워진 원하는 크기의 텐서 만들기
x = torch.FloatTensor(3,2)

x

tensor([[1.1490e-29, 4.5719e-41],
        [1.1490e-29, 4.5719e-41],
        [0.0000e+00, 0.0000e+00]])

### 넘파이 호환

In [8]:
import torch
import numpy as np

In [9]:
# 넘파이 배열 생성
x = np.array([[1,2],
              [3,4]])
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [10]:
# 파이토치 텐서로 변환
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [11]:
# 넘파이 배열로 변환
x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


### 텐서 타입 변환

In [12]:
# Float 타입을 Long 타입으로 변환하기
ft.long()

tensor([[1, 2],
        [3, 4]])

In [13]:
# Long 타입을 Float 타입으로 변환하기
lt.float()

tensor([[1., 2.],
        [3., 4.]])

### 텐서 크기 구하기

In [14]:
# 3*2*2 텐서 선언하기
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                       [[5,6],
                        [7,8]],
                       [[9,10],
                        [11,12]]])

In [15]:
# 크기 확인
print(x.size())

torch.Size([3, 2, 2])


In [16]:
print(x.shape)

torch.Size([3, 2, 2])


In [17]:
# 특정 차원의 크기 확인하기
print(x.size(1))

2


In [18]:
print(x.shape[1])

2


In [19]:
# 텐서 차원의 개수 확인하기
print(x.dim())

3


In [21]:
print(len(x.size()))

3



### 요소별 산술연산

In [22]:
import torch

In [23]:
# 두 개의 텐서 생성하기
a = torch.FloatTensor([[1,2],
                       [3,4]])
b = torch.FloatTensor([[2,2],
                       [3,3]])

In [24]:
# 텐서 간 덧셈
a+b

tensor([[3., 4.],
        [6., 7.]])

In [30]:
# 사칙연산
print(a+b) # 덧셈
print(a-b) # 뺄셈
print(a*b) # 곱셈
print(a/b) # 나눗셈

tensor([[3., 4.],
        [6., 7.]])
tensor([[-1.,  0.],
        [ 0.,  1.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])


In [31]:
# 제곱 연산
a**b

tensor([[ 1.,  4.],
        [27., 64.]])

In [32]:
# 논리 연산
a == b

tensor([[False,  True],
        [ True, False]])

### 인플레이스 연산
- 기존 텐서에 결과가 저장됨
- 함수명 뒤에 밑줄(_)이 붙음

In [33]:
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [34]:
# a.mul(b) = a*b
print(a.mul(b))

tensor([[ 2.,  4.],
        [ 9., 12.]])


In [35]:
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [36]:
print(a.mul_(b))

tensor([[ 2.,  4.],
        [ 9., 12.]])


In [37]:
print(a)

tensor([[ 2.,  4.],
        [ 9., 12.]])


### 차원축소 연산 : 합과 평균

In [38]:
# 텐서 선언
x = torch.FloatTensor([[1,2],
                       [3,4]])

In [39]:
# 합
print(x.sum())

tensor(10.)


In [40]:
# 평균
print(x.mean())

tensor(2.5000)


In [42]:
# dim인자에 원하는 연산의 차원 넣어줄 수 있음
# dim 인자의 값은 없어지는 차원
print(x.sum())
print(x.sum(dim=0))

tensor(10.)
tensor([4., 6.])


In [43]:
print(x.sum(dim=-1))

tensor([3., 7.])
